spring:
  config:
    import: classpath:secret.yml

  jpa:
    hibernate:
      ddl-auto: update

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    kea.dpang.auth.feign.*: DEBUG